routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('/home');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');

Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');

Route::resource('bancos', 'BancoController');

Route::resource('clasificados', 'ClasificadoController');

//cobranzas
Route::get('cobranzas/muestraCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class, 'muestraCobranza'])->name('muestraCobranza');

Route::get('cobranzas/createCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class,
'createCobranza'])->name('createCobranza');

Route::get('cobranzas/impagos/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\CobranzaController::class, 'impagos'])->name('impagos');

//Route::get('cobranzas/reporteImpagos/{cobranzas}', [App\Http\Controllers\CobranzaController::class, 'reporteImpagos'])->name('reporteImpagos');
Route::get('cobranzas/enviaMailCobranzaUno/{id}/{motivo}', [App\Http\Controllers\MailController::class, 'enviaMailCobranzaUno'])->name('enviaMailCobranzaUno');


Route::resource('cobranzas', 'CobranzaController');
Route::resource('empresas', 'EmpresaController');
Route::resource('empseguros', 'EmpseguroController');

Route::resource('marcas', 'MarcaController');
//modelos

Route::get('modelos/creaModelo/{marca}', [App\Http\Controllers\ModeloController::class, 'creaModelo'])->name('creaModelo');

Route::get('modelos/muestraModelos/{marca}', [App\Http\Controllers\ModeloController::class, 'muestraModelos'])->name('muestraModelos');
Route::get('modelos/borramodelos/{id}', [App\Http\Controllers\ModeloController::class, 'destroy'])->name('borramodelos');

Route::resource('modelos', 'ModeloController');



Route::get('clientes/municipiosbyprovincias/{id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias'])->name('municipiosbyprovincias');

Route::get('clientes/{cliente}/municipiosbyprovincias2/{provincia_id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias2'])->name('municipiosbyprovincias2');

Route::get('clientes/clientesEspera', [App\Http\Controllers\ClienteController::class, 'clientesEspera'])->name('clientesEspera');
Route::get('clientes/muestraModal', [App\Http\Controllers\ClienteController::class, 'muestraModal'])->name('muestraModal');

Route::resource('clientes', 'ClienteController');
Route::resource('gastos', 'GastoController');

//municipios

Route::get('municipios/creaMunicipio/{provincia}', [App\Http\Controllers\MunicipioController::class, 'creaMunicipio'])->name('creaMunicipio');
Route::get('municipios/muestraLocalidad/{provincia}', [App\Http\Controllers\MunicipioController::class, 'muestraLocalidad'])->name('muestraLocalidad');
Route::resource('municipios', 'MunicipioController');

//pagos
Route::get('pagos/muestraPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPago'])->name('muestraPago');
Route::get('pagos/createPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'createPago'])->name('createPago');

Route::delete('pagos/borraPago/{id}/{retorno}', [App\Http\Controllers\PagoController::class, 'borraPago'])->name('borraPago');

Route::get('pagos/editaPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'editaPago'])->name('editaPago');
Route::get('pagos/muestraPagoExtension/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPagoExtension'])->name('muestraPagoExtension');

Route::resource('pagos', 'PagoController');

//prestamos

Route::name('print')->get('/imprimir/{id}/{vehiculo_id}', 'GeneradorController@imprimir');

Route::get('prestamos/editaprestamo/{id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'editaprestamo'])->name('editaprestamo');
Route::get('prestamos/creaprestamo/{id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamo'])->name('creaprestamo');

Route::get('prestamos/listaprestamos/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamos'])->name('listaprestamos');
Route::get('prestamos/listaprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamoscliente'])->name('listaprestamoscliente');
Route::get('prestamos/ultimoprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'ultimoprestamoscliente'])->name('ultimoprestamoscliente');
//para mostrar las extensiones 02/10/2024

Route::get('prestamos/creaprestamoextension/{prestamo_id}/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamoextension'])->name('creaprestamoextension');
Route::get('prestamos/borraExtension/{prestamo_id}/{padre_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'borraExtension'])->name('borraExtension');

Route::resource('prestamos', 'PrestamoController');
Route::resource('provincias', 'ProvinciaController');

//vehiculos

Route::get('vehiculos/editavehiculo/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'editavehiculo'])->name('editavehiculo');
Route::get('vehiculos/createcliente/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'createcliente'])->name('createcliente');

Route::get('vehiculos/editavehiculo/{cliente}/modelosxmarcas2/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas2'])->name('modelosxmarcas2');

Route::get('vehiculos/createcliente/{cliente}/modelosxmarcas/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas'])->name('modelosxmarcas');

Route::get('vehiculos/listavehiculos/{idcliente}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'listavehiculos'])->name('listavehiculos');


//itv
Route::post('itv/muestraitv', [App\Http\Controllers\ItvController::class, 'muestraItv'])->name('muestraItv');
//Route::get('itv/elije', [App\Http\Controllers\ItvController::class, 'listaItv'])->name('listaItv');;
Route::resource('itv', 'ItvController');


//carnet de conducir
Route::post('carnet/muestraCarnet', [App\Http\Controllers\CarnetController::class, 'muestraCarnet'])->name('muestraCarnet');
Route::resource('carnet', 'CarnetController');

//polizas
Route::post('poliza/muestrapolizas', [App\Http\Controllers\PolizaController::class, 'muestraPolizas'])->name('muestraPolizas');
Route::resource('poliza', 'PolizaController');
//multas

Route::get('multa/createMultas/{id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'createMultas'])->name('createMultas');

Route::get('multa/muestraMultas/{id}/{motivo}/{vehiculo_id}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultas'])->name('muestraMultas');

Route::get('multa/general/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultasGeneral'])->name('muestraMultasGeneral');

Route::delete('multa/borraMulta/{id}/{cliente_id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'borraMulta'])->name('borraMulta');

Route::get('multa/editaMulta/{id}/{retorno}', [App\Http\Controllers\MultaController::class, 'editaMulta'])->name('editaMulta');

Route::resource('multas', 'MultaController');

Route::resource('vehiculos', 'VehiculoController');
Route::resource('users', 'UserController');

Route::get('muestraContratos/{cliente_id}/{prestamo_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\ContratoController::class, 'muestraContratos'])->name('muestraContratos');



//-----contratos ----
Route::get('contrato/index', [App\Http\Controllers\ContratoController::class, 'index'])->name('contratos');

    Route::name('CompraVenta')->get('/CompraVenta/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@CompraVenta');
    Route::name('DatosOperacion')->get('/DatosOperacion/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DatosOperacion');

    Route::name('DocumentoEntrega')->get('/DocumentoEntrega/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DocumentoEntrega');
    Route::name('EdicionCliente')->get('/EdicionCliente/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@EdicionCliente');
    Route::name('ContratoArrendamiento')->get('/ContratoArrendamiento/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@ContratoArrendamiento');
    Route::name('MandatoEspecifico')->get('/MandatoEspecifico/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@MandatoEspecifico');
    Route::name('ImpagoIndividual')->get('/ImpagoIndividual/{id}/{prestamo_id}', 'GeneradorController@ImpagoIndividual');

//mail

Route::get('mail/enviaMailPoliza', [App\Http\Controllers\MailController::class, 'enviaMailPoliza'])->name('enviaMailPoliza');

Route::get('mail/enviaMailitv', [App\Http\Controllers\MailController::class, 'enviaMailitv'])->name('enviaMailitv');
Route::get('mail/enviaMailCobranza', [App\Http\Controllers\MailController::class, 'enviaMailCobranza'])->name('enviaMailCobranza');

//reportes de rentabilidad

Route::get('rentabilidad/rentageneral/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\RentabilidadController::class, 'muestraRentabilidad'])->name('muestraRentabilidad');

app/Models/Municipio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Municipio
 *
 * @property $id
 * @property $provincia_id
 * @property $municipio_id
 * @property $nombre
 * @property $created_at
 * @property $updated_at
 *
 * @property Cliente[] $clientes
 * @property Provincia $provincia
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Municipio extends Model
{
    
    static $rules = [
		'provincia_id' => 'required',
		'nombre' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['provincia_id','nombre'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clientes()
    {
        return $this->hasMany('App\Models\Cliente', 'municipio_id', 'id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function provincia()
    {
        return $this->hasOne('App\Models\Provincia', 'id', 'provincia_id');
    }
    

}

app/Http/Controllers/MunicipioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Municipio;
use App\Models\Provincia;
use App\Models\Cliente;
use Illuminate\Http\Request;

/**
 * Class MunicipioController
 * @package App\Http\Controllers
 */
class MunicipioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $municipios = Municipio::paginate();

        return view('municipio.index', compact('municipios'))
            ->with('i', (request()->input('page', 1) - 1) * $municipios->perPage());
    }
    public function muestraLocalidad(Request $request, $provincia)
    {
        $buscar=$request->buscar;
        if($buscar==''){
        //$municipios = Municipio::paginate();
            $municipios=Municipio::join('provincias','municipios.provincia_id','=','provincias.id')
            ->where('provincias.id','=',$provincia)
            ->select('provincias.id as provincia','provincias.nombre as nom','municipios.*')
            ->paginate();
        }else{
            $municipios=Municipio::join('provincias','municipios.provincia_id','=','provincias.id')
            ->where('provincias.id','=',$provincia)
            ->where('municipios.nombre','like','%'.$buscar.'%')
            ->select('provincias.id as provincia','provincias.nombre as nom','municipios.*')
            ->paginate();
        }
        return view('municipio.index', compact('municipios','provincia'))
            ->with('i', (request()->input('page', 1) - 1) * $municipios->perPage());
    }
     public function creaMunicipio($provincia)
    {
        $municipio = new Municipio();
        $municipio->provincia_id=$provincia;
        return view('municipio.create', compact('municipio','provincia'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $municipio = new Municipio();
        return view('municipio.create', compact('municipio'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Municipio::$rules);

        $municipio = Municipio::create($request->all());
        $provincia=$request->provincia_id;

        return redirect()->route('muestraLocalidad',compact('provincia'))
            ->with('success', 'Localidad creada con Exito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $municipio = Municipio::find($id);

        return view('municipio.show', compact('municipio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $municipio = Municipio::find($id);
        $provincia=$municipio->provincia_id;

        return view('municipio.edit', compact('municipio','provincia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Municipio $municipio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Municipio $municipio)
    {
        request()->validate(Municipio::$rules);
        $municipio->update($request->all());
        $provincia=$municipio->provincia_id;

        return redirect()
    ->action('MunicipioController@muestraLocalidad', $provincia)
    ->with('success', 'Localidad modificada con Exito.');


    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $clientes=Cliente::where('clientes.municipio_id','=',$id)->selectRaw('count(*) as total')->get();
        $tclientes=0;
        foreach ($clientes as $gas) {
            $tclientes=$gas->total;
        }
        $municipio = Municipio::find($id);
        $provincia=$municipio->provincia_id;
        if($tclientes==0){
            $municipio=$municipio->delete();
            $smj='Localidad eliminada con Exito';
        }else{
            $smj='No se puede eliminar porque tiene Clientes asociados';
        }
        
        return redirect()
    ->action('MunicipioController@muestraLocalidad', $provincia)
    ->with('success', $smj);

        /*return redirect()->route('municipios.index')
            ->with('success', $smj);
            */
    }
}

resources/views/municipio/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Municipio
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Nueva') }} Localidad</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('municipios.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('municipio.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/municipio/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Municipio
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Modificar') }} Localidad</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('municipios.update', $municipio->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('municipio.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/municipio/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            <!--{{ Form::label('provincia_id') }}-->
            {{ Form::hidden('provincia_id', $municipio->provincia_id, ['class' => 'form-control' . ($errors->has('provincia_id') ? ' is-invalid' : ''), 'placeholder' => 'Provincia Id']) }}
            {!! $errors->first('provincia_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            <!--{{ Form::label('municipio_id') }}-->
            {{ Form::hidden('id', $municipio->id, ['class' => 'form-control' . ($errors->has('id') ? ' is-invalid' : ''), 'placeholder' => 'Municipio Id']) }}
            {!! $errors->first('id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Localidad') }}
            {{ Form::text('nombre', $municipio->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('Guardar') }}</button>
        <a href="{{route('muestraLocalidad',$provincia)}}"  ><div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a>
    </div>
</div>

resources/views/municipio/index.blade.php
@extends('layouts.app')

@section('template_title')
    Municipio
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Localidades') }}
                            </span>

                                <a href="{{route('provincias.index')}}"  ><div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a>
                             <div class="float-right">
                                <a href="{{ route('creaMunicipio',$provincia) }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Nueva Localidad') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <form id="myForm" method="GET" action="{{ route('muestraLocalidad',$provincia) }}"  role="form" enctype="multipart/form-data">
                            @csrf
                            <input type="text" name="buscar" value="">
                            <button type="submit" class="btn btn-primary"><i></i> {{ __('Buscar') }}</button>
                        </form>
                        {!! $municipios->links() !!}
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>Núm</th>
                                        
										<th>Provincia</th>
										<th>Localidad</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($municipios as $municipio)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $municipio->nom }}</td>
											<td>{{ $municipio->nombre }}</td>

                                            <td>
                                                <form action="{{ route('municipios.destroy',$municipio->id) }}" method="POST" id="borrar">
                                                    <!--<a class="btn btn-sm btn-primary " href="{{ route('municipios.show',$municipio->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('Show') }}</a>-->
                                                    <a class="btn btn-sm btn-success" href="{{ route('municipios.edit',$municipio->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Editar') }}</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <a  class="btn btn-danger btn-sm" onclick="aviso({{$municipio->id}});"><i class="fa fa-fw fa-trash">{{ __('Borrar') }}</i></a>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $municipios->links() !!}
            </div>
        </div>
    </div>
@endsection
<script type="text/javascript">
    function aviso(id){
        var resp=confirm("¿Está seguro de eliminar este Municipio?");
        if(!resp){
            event.preventDefault();
            event.returnValue = '';
        }else{
            let url ="<?php echo env('APP_URL'); ?>";
            url=url +'/municipios/'+id;
            document.getElementById("borrar").action = url;
            document.getElementById("borrar").submit();
        }
    }
</script>

resources/views/municipio/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $municipio->name ?? "{{ __('Show') Municipio" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Municipio</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('municipios.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Provincia Id:</strong>
                            {{ $municipio->provincia_id }}
                        </div>
                        <div class="form-group">
                            <strong>Municipio Id:</strong>
                            {{ $municipio->municipio_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $municipio->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection