routes/web.php
Route::resource('clasificados', 'ClasificadoController');

//cobranzas
Route::get('cobranzas/muestraCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class, 'muestraCobranza'])->name('muestraCobranza');

Route::get('cobranzas/createCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class,
'createCobranza'])->name('createCobranza');

Route::get('cobranzas/impagos/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\CobranzaController::class, 'impagos'])->name('impagos');

//Route::get('cobranzas/reporteImpagos/{cobranzas}', [App\Http\Controllers\CobranzaController::class, 'reporteImpagos'])->name('reporteImpagos');
Route::get('cobranzas/enviaMailCobranzaUno/{id}/{motivo}', [App\Http\Controllers\MailController::class, 'enviaMailCobranzaUno'])->name('enviaMailCobranzaUno');


Route::resource('cobranzas', 'CobranzaController');
Route::resource('empresas', 'EmpresaController');
Route::resource('empseguros', 'EmpseguroController');

Route::resource('marcas', 'MarcaController');
//modelos

Route::get('modelos/creaModelo/{marca}', [App\Http\Controllers\ModeloController::class, 'creaModelo'])->name('creaModelo');

Route::get('modelos/muestraModelos/{marca}', [App\Http\Controllers\ModeloController::class, 'muestraModelos'])->name('muestraModelos');
Route::get('modelos/borramodelos/{id}', [App\Http\Controllers\ModeloController::class, 'destroy'])->name('borramodelos');

Route::resource('modelos', 'ModeloController');



Route::get('clientes/municipiosbyprovincias/{id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias'])->name('municipiosbyprovincias');

Route::get('clientes/{cliente}/municipiosbyprovincias2/{provincia_id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias2'])->name('municipiosbyprovincias2');

Route::get('clientes/clientesEspera', [App\Http\Controllers\ClienteController::class, 'clientesEspera'])->name('clientesEspera');
Route::get('clientes/muestraModal', [App\Http\Controllers\ClienteController::class, 'muestraModal'])->name('muestraModal');

Route::resource('clientes', 'ClienteController');
Route::resource('gastos', 'GastoController');

//municipios

Route::get('municipios/creaMunicipio/{provincia}', [App\Http\Controllers\MunicipioController::class, 'creaMunicipio'])->name('creaMunicipio');
Route::get('municipios/muestraLocalidad/{provincia}', [App\Http\Controllers\MunicipioController::class, 'muestraLocalidad'])->name('muestraLocalidad');
Route::resource('municipios', 'MunicipioController');

//pagos
Route::get('pagos/muestraPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPago'])->name('muestraPago');
Route::get('pagos/createPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'createPago'])->name('createPago');

Route::delete('pagos/borraPago/{id}/{retorno}', [App\Http\Controllers\PagoController::class, 'borraPago'])->name('borraPago');

Route::get('pagos/editaPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'editaPago'])->name('editaPago');
Route::get('pagos/muestraPagoExtension/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPagoExtension'])->name('muestraPagoExtension');

Route::resource('pagos', 'PagoController');

//prestamos

Route::name('print')->get('/imprimir/{id}/{vehiculo_id}', 'GeneradorController@imprimir');

Route::get('prestamos/editaprestamo/{id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'editaprestamo'])->name('editaprestamo');
Route::get('prestamos/creaprestamo/{id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamo'])->name('creaprestamo');

Route::get('prestamos/listaprestamos/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamos'])->name('listaprestamos');
Route::get('prestamos/listaprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamoscliente'])->name('listaprestamoscliente');
Route::get('prestamos/ultimoprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'ultimoprestamoscliente'])->name('ultimoprestamoscliente');
//para mostrar las extensiones 02/10/2024

Route::get('prestamos/creaprestamoextension/{prestamo_id}/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamoextension'])->name('creaprestamoextension');
Route::get('prestamos/borraExtension/{prestamo_id}/{padre_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'borraExtension'])->name('borraExtension');

Route::resource('prestamos', 'PrestamoController');
Route::resource('provincias', 'ProvinciaController');

//vehiculos

Route::get('vehiculos/editavehiculo/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'editavehiculo'])->name('editavehiculo');
Route::get('vehiculos/createcliente/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'createcliente'])->name('createcliente');

Route::get('vehiculos/editavehiculo/{cliente}/modelosxmarcas2/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas2'])->name('modelosxmarcas2');

Route::get('vehiculos/createcliente/{cliente}/modelosxmarcas/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas'])->name('modelosxmarcas');

Route::get('vehiculos/listavehiculos/{idcliente}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'listavehiculos'])->name('listavehiculos');


//itv
Route::post('itv/muestraitv', [App\Http\Controllers\ItvController::class, 'muestraItv'])->name('muestraItv');
//Route::get('itv/elije', [App\Http\Controllers\ItvController::class, 'listaItv'])->name('listaItv');;
Route::resource('itv', 'ItvController');


//carnet de conducir
Route::post('carnet/muestraCarnet', [App\Http\Controllers\CarnetController::class, 'muestraCarnet'])->name('muestraCarnet');
Route::resource('carnet', 'CarnetController');

//polizas
Route::post('poliza/muestrapolizas', [App\Http\Controllers\PolizaController::class, 'muestraPolizas'])->name('muestraPolizas');
Route::resource('poliza', 'PolizaController');
//multas

Route::get('multa/createMultas/{id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'createMultas'])->name('createMultas');

Route::get('multa/muestraMultas/{id}/{motivo}/{vehiculo_id}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultas'])->name('muestraMultas');

Route::get('multa/general/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultasGeneral'])->name('muestraMultasGeneral');

Route::delete('multa/borraMulta/{id}/{cliente_id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'borraMulta'])->name('borraMulta');

Route::get('multa/editaMulta/{id}/{retorno}', [App\Http\Controllers\MultaController::class, 'editaMulta'])->name('editaMulta');

Route::resource('multas', 'MultaController');

Route::resource('vehiculos', 'VehiculoController');
Route::resource('users', 'UserController');

Route::get('muestraContratos/{cliente_id}/{prestamo_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\ContratoController::class, 'muestraContratos'])->name('muestraContratos');



//-----contratos ----
Route::get('contrato/index', [App\Http\Controllers\ContratoController::class, 'index'])->name('contratos');

    Route::name('CompraVenta')->get('/CompraVenta/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@CompraVenta');
    Route::name('DatosOperacion')->get('/DatosOperacion/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DatosOperacion');

    Route::name('DocumentoEntrega')->get('/DocumentoEntrega/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DocumentoEntrega');
    Route::name('EdicionCliente')->get('/EdicionCliente/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@EdicionCliente');
    Route::name('ContratoArrendamiento')->get('/ContratoArrendamiento/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@ContratoArrendamiento');
    Route::name('MandatoEspecifico')->get('/MandatoEspecifico/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@MandatoEspecifico');
    Route::name('ImpagoIndividual')->get('/ImpagoIndividual/{id}/{prestamo_id}', 'GeneradorController@ImpagoIndividual');

//mail

Route::get('mail/enviaMailPoliza', [App\Http\Controllers\MailController::class, 'enviaMailPoliza'])->name('enviaMailPoliza');

Route::get('mail/enviaMailitv', [App\Http\Controllers\MailController::class, 'enviaMailitv'])->name('enviaMailitv');
Route::get('mail/enviaMailCobranza', [App\Http\Controllers\MailController::class, 'enviaMailCobranza'])->name('enviaMailCobranza');

//reportes de rentabilidad

Route::get('rentabilidad/rentageneral/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\RentabilidadController::class, 'muestraRentabilidad'])->name('muestraRentabilidad');
Route::get('rentabilidad/individual/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\RentabilidadController::class, 'RentabilidadIndividual'])->name('RentabilidadIndividual');

Route::get('rentabilidad/historial/{id}', [App\Http\Controllers\RentabilidadController::class, 'historial'])->name('historial');
//manuales
Route::get('manuales/index', [App\Http\Controllers\ManualesController::class, 'index'])->name('manuales');
Route::get('manuales/download/{archivo}', [App\Http\Controllers\ManualesController::class, 'download'])->name('download');

//documentos de cada cliente
Route::delete('documento/destroyDocumento/{id}/{cliente_id}/{retorno}/{vehiculo_id}', [App\Http\Controllers\DocumentoController::class, 'destroyDocumento'])->name('destroyDocumento');
Route::get('documento/createDocumento/{cliente_id}/{retorno}/{vehiculo_id}', [App\Http\Controllers\DocumentoController::class, 'createDocumento'])->name('createDocumento');

app/Models/Vehiculo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Vehiculo
 *
 * @property $id
 * @property $cliente_id
 * @property $marca_id
 * @property $modelo_id
 * @property $empseguro_id
 * @property $nano
 * @property $itv
 * @property $fcompra
 * @property $fvencseguro
 * @property $finicseguro
 * @property $tipo_id
 * @property $frecuencia
 * @property $valoracion
 * @property $cuotaunica
 * @property $situacion_id
 * @property $poliza
 * @property $matricula
 * @property $bastidor
 * @property $kilometros
 * @property $fmatricula
 * @property $tcombustible
 * @property $observacion
 * @property $created_at
 * @property $updated_at
 *
 * @property Cliente $cliente
 * @property Empseguro $empseguro
 * @property Marca $marca
 * @property Modelo $modelo
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Vehiculo extends Model
{
    
    static $rules = [
        /*
		'cliente_id' => 'required',
		'marca_id' => 'required',
		'modelo_id' => 'required|gt:0',
		'empseguro_id' => 'required',
        'situacion_id' => 'required',
		'nano' => 'required',
		'itv' => 'required|max:10',
		'fvencseguro' => 'required|max:10',
		'finicseguro' => 'required|max:10',
        'fcarnet' => 'required|max:10',
		'valoracion' => 'required',
		'cuotaunica' => 'required|gt:-1',
		'poliza' => 'required',
		'matricula' => 'required',
        'bastidor' => 'required|MAX:20',
        'kilometros' => 'required',
        'fmatricula' => 'required|max:10',
        */
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['cliente_id','marca_id','modelo_id','empseguro_id','nano','itv','fcompra','fvencseguro','finicseguro','tipo_id','frecuencia','valoracion','cuotaunica','situacion_id','poliza','matricula','bastidor','kilometros','fmatricula','tcombustible','observacion'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function cliente()
    {
        return $this->hasOne('App\Models\Cliente', 'id', 'cliente_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function empseguro()
    {
        //return $this->hasOne('App\Models\Empseguro', 'id', 'empseguro_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function marca()
    {
        //return $this->hasOne('App\Models\Marca', 'id', 'marca_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function modelo()
    {
        //return $this->hasOne('App\Models\Modelo', 'id', 'modelo_id');
    }
}

resources/views/vehiculo/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Vehiculo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Nuevo') }} Vehiculo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('vehiculos.store') }}"  role="form" enctype="multipart/form-data" onkeydown="return event.key != 'Enter';">
                            
                            @csrf
                            <?php
                                $nuevo=1;
                            ?>
                            <input type="hidden" name="nuevo" id="nuevo" value="<?php echo $nuevo; ?>">

                            @include('vehiculo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/vehiculo/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Vehiculo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Modificar') }} Vehiculo</span>
                    </div>
                    <div class="card-body">
                        <!--onkeydown="return event.key != 'Enter';"-->
                        <form method="POST" action="{{ route('vehiculos.update', $vehiculo->id) }}"  role="form" enctype="multipart/form-data" onkeydown="return event.key != 'Enter';">
                            
                            {{ method_field('PATCH') }}
                            @csrf
                            <?php
                                $nuevo=0;
                            ?>
                            <button type="submit" disabled hidden aria-hidden="true"></button>
                            <input type="hidden" name="nuevo" id="nuevo" value="<?php echo $nuevo; ?>">

                            @include('vehiculo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/vehiculo/index.blade.php
@extends('layouts.app')

@section('template_title')
    Vehiculo
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">

                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <span id="card_title">
                                {{ __('Vehiculos') }}
                                @if($retorno>0)
                                <div id='iden'></div>
                                @endif
                            </span>
                        <div align="center">
                            @if($retorno==0)
                            <a href="{{route('home')}}">
                            @elseif($retorno==1)
                            <a href="{{route('clientes.index')}}">
                                @elseif($retorno==2)
                                <a href="{{route('clientes.edit',$idcliente)}}">
                                <?php //$retorno=4; ?>
                            @else
                                <a href="javascript.document.history.back(-1)">
                            @endif
                                <div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a>
                        </div>
                        <div>

                        </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <!--botones-->

    @if(!isset($retorno) || $retorno>0)
        <a href="{{ route('clientes.index') }}" ><div class="grid-item2 btn btn-primary">Clientes</div></a>
        <a href="{{route('listaprestamoscliente',[$idcliente,0,4])}}" ><div class="grid-item4 btn btn-primary">Empeños</div></a>
        <a href="{{route('muestraDocumentos',[$idcliente,4,0])}}" ><div class="grid-item4 btn btn-primary">Documentos</div></a>
        <a href="{{ route('createcliente',[$idcliente,4]) }}" ><div class="grid-item5 btn btn-primary">Agregar Vehículo</div></a>
    @endif
                        {!! $vehiculos->links() !!}
                        <div class="table-responsive">
                            @if(!isset($retorno) || $retorno==0)
                            <form action="{{route('listavehiculos',[$idcliente,$retorno])}}">
                                <input type="text" name="texto" class="form-label" style="width:200px;">
                                <button type="submit" class="btn btn-primary">Buscar</button>
                              </form>
                              @endif
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
										<th>Núm</th>
										<!--<th>Empresa</th>
										<th>Nombre</th>
										<th>DNI</th>
                                        -->
										<th>Marca/Modelo</th>
										<th>Matrícula</th>
                                        <th>Sit.<br> Carga</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                    $cadena=array();
                                    $cad=0;
                                @endphp
                                    @foreach ($vehiculos as $vehiculo)
                                    @php
                                        echo "<script>";
                                        echo '$("#iden").html("<a href=\"'.route('clientes.edit',$idcliente).'\">DNI:<b>'.$vehiculo->dni.'</b>Nombre:<b>'.$vehiculo->nombre.'</b></a>")';
                                        echo "</script>";
                                    @endphp


                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            <!--<td>{{ $vehiculo->nombre }}</td>
											<td>{{ $vehiculo->dni }}</td>
                                            -->
                                            <td>{{ $vehiculo->mar }}/{{ $vehiculo->mod }}</td>
                                            <td>{{ $vehiculo->matricula}}</td>
                                            <td>
                                                @if(is_null($vehiculo->idveh))
                                                    <img src="{{ asset('images/rojo.jpg') }}" width="28" height="25">
                                                @else
                                                    <?php
                                                        $cad++;
                                                        $falta=cuenta_faltantes('vehiculos',$vehiculo->id,1,$cadena,$cad);
                                                    ?>
                                                    @if($falta==0)
                                                    <img src="{{ asset('images/verde.jpg') }}" width="28" height="25">
                                                    @else
                                                    <a href="#"  data-toggle="modal" data-target="#myModal{{$cad}}">
                                                        <img src="{{ asset('images/rojo.jpg') }}" width="28" height="25">
                                                    </a>
                                                    @endif
                                                @endif
                                                <div class="modal " id="myModal{{$cad}}" role="dialog" >
                                                    <div class="modal-dialog">
                                                      <!-- Modal -->
                                                      <div class="modal-content" style="height:300px;width:300px;right: 350px;">
                                                        <div class="modal-header">
                                                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                          <h4 class="modal-title">Datos Faltantes</h4>
                                                        </div>
                                                        <div class="modal-body" >
                                                            <div>
                                                                @php
                                                                    echo $cadena[$cad];
                                                                @endphp
                                                              </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
											<td>
                                            @if(!is_null($vehiculo->idveh))
                                                <form action="{{ route('vehiculos.destroy',$vehiculo->idveh) }}" method="POST" id="borrar">
                                                    <input type="hidden" name="retorno" value="{{$retorno}}">
                                        <a class="btn btn-sm btn-success btnn" href="{{ route('editavehiculo',[$vehiculo->idveh,$retorno]) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Editar') }}</a>
                                        <a class="btn btn-sm empenos_btn btnn" href="{{ route('listaprestamoscliente',[$vehiculo->cliente_id,$vehiculo->id,$retorno])}}"><i class="fa fa-fw fa-edit"></i> {{ __('Empeños') }}</a>
                                        <a class="btn btn-sm multas_btn btnn"  href="{{ route('muestraMultas',[$vehiculo->idcliente,0,$vehiculo->idveh,$retorno]) }}" ><i class="fa fa-fw fa-edit"></i> {{ __('Multas') }}</a>
                                        <a class="btn btn-sm impuestos_btn btnn"  href="{{ route('listaImpuestos',[$vehiculo->id,8]) }}" ><i class="fa fa-fw fa-edit"></i> {{ __('Impuestos') }}</a>
                                        <a class="btn btn-sm gastos_btn btnn"  href="{{ route('muestraMultas',[$vehiculo->idcliente,1,$vehiculo->idveh,$retorno]) }}" ><i class="fa fa-fw fa-edit"></i> {{ __('Gastos') }}</a>

                                                @csrf
                                                @method('DELETE')
                                                <a onclick="aviso({{$vehiculo->idveh}});" class="btn btn-danger btn-sm btnn"><i class="fa fa-fw fa-trash">{{ __('Borrar') }}</i> </a>
                                                </form>
                                            @else
                                                    <a class="btn btn-sm btn-success" href="{{ route('createcliente',[$vehiculo->idcliente,2]) }}" style="background-color:blue;color:white;"><i class="fa fa-fw fa-edit" ></i> {{ __('Nuevo') }}</a>
                                            @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $vehiculos->links() !!}
            </div>
        </div>
    </div>
@endsection
<script src="{{asset('modal/assets/jquery-1.12.4-jquery.min.js')}}"></script>
<script src="{{asset('modal/assets/jquery.validate.min.js')}}"></script>
<script src="{{asset('modal/dist/js/bootstrap.min.js')}}"></script>
<script type="text/javascript">
    function aviso(id){
        var resp=confirm("¿Está seguro de eliminar este Vehículo?");
        if(!resp){
            event.preventDefault();
            event.returnValue = '';
        }else{
            let url ="<?php echo env('APP_URL'); ?>";
            url=url +'/vehiculos/'+id;
            document.getElementById("borrar").action = url;
            document.getElementById("borrar").submit();

        }
    }
</script>

resources/views/vehiculo/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $vehiculo->name ?? "{{ __('Show') Vehiculo" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Vehiculo</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('vehiculos.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Cliente Id:</strong>
                            {{ $vehiculo->cliente_id }}
                        </div>
                        <div class="form-group">
                            <strong>Marca Id:</strong>
                            {{ $vehiculo->marca_id }}
                        </div>
                        <div class="form-group">
                            <strong>Modelo Id:</strong>
                            {{ $vehiculo->modelo_id }}
                        </div>
                        <div class="form-group">
                            <strong>Empseguro Id:</strong>
                            {{ $vehiculo->empseguro_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nano:</strong>
                            {{ $vehiculo->nano }}
                        </div>
                        <div class="form-group">
                            <strong>Itv:</strong>
                            {{ $vehiculo->itv }}
                        </div>
                        <div class="form-group">
                            <strong>Fcompra:</strong>
                            {{ $vehiculo->fcompra }}
                        </div>
                        <div class="form-group">
                            <strong>Fvencseguro:</strong>
                            {{ $vehiculo->fvencseguro }}
                        </div>
                        <div class="form-group">
                            <strong>Finicseguro:</strong>
                            {{ $vehiculo->finicseguro }}
                        </div>
                        <div class="form-group">
                            <strong>Tiposeguro:</strong>
                            {{ $vehiculo->tiposeguro }}
                        </div>
                        <div class="form-group">
                            <strong>Frecuencia:</strong>
                            {{ $vehiculo->frecuencia }}
                        </div>
                        <div class="form-group">
                            <strong>Valoracion:</strong>
                            {{ $vehiculo->valoracion }}
                        </div>
                        <div class="form-group">
                            <strong>Cuotaunica:</strong>
                            {{ $vehiculo->cuotaunica }}
                        </div>
                        <div class="form-group">
                            <strong>Situacion:</strong>
                            {{ $vehiculo->situacion }}
                        </div>
                        <div class="form-group">
                            <strong>Poliza:</strong>
                            {{ $vehiculo->poliza }}
                        </div>
                        <div class="form-group">
                            <strong>Matricula:</strong>
                            {{ $vehiculo->matricula }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection