routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('/home');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');

Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');

Route::resource('bancos', 'BancoController');

Route::resource('clasificados', 'ClasificadoController');

//cobranzas
Route::get('cobranzas/muestraCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class, 'muestraCobranza'])->name('muestraCobranza');

Route::get('cobranzas/createCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class,
'createCobranza'])->name('createCobranza');

Route::get('cobranzas/impagos/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\CobranzaController::class, 'impagos'])->name('impagos');

//Route::get('cobranzas/reporteImpagos/{cobranzas}', [App\Http\Controllers\CobranzaController::class, 'reporteImpagos'])->name('reporteImpagos');
Route::get('cobranzas/enviaMailCobranzaUno/{id}/{motivo}', [App\Http\Controllers\MailController::class, 'enviaMailCobranzaUno'])->name('enviaMailCobranzaUno');


Route::resource('cobranzas', 'CobranzaController');
Route::resource('empresas', 'EmpresaController');
Route::resource('empseguros', 'EmpseguroController');

Route::resource('marcas', 'MarcaController');
//modelos

Route::get('modelos/creaModelo/{marca}', [App\Http\Controllers\ModeloController::class, 'creaModelo'])->name('creaModelo');

Route::get('modelos/muestraModelos/{marca}', [App\Http\Controllers\ModeloController::class, 'muestraModelos'])->name('muestraModelos');
Route::get('modelos/borramodelos/{id}', [App\Http\Controllers\ModeloController::class, 'destroy'])->name('borramodelos');

Route::resource('modelos', 'ModeloController');



Route::get('clientes/municipiosbyprovincias/{id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias'])->name('municipiosbyprovincias');

Route::get('clientes/{cliente}/municipiosbyprovincias2/{provincia_id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias2'])->name('municipiosbyprovincias2');

Route::get('clientes/clientesEspera', [App\Http\Controllers\ClienteController::class, 'clientesEspera'])->name('clientesEspera');
Route::get('clientes/muestraModal', [App\Http\Controllers\ClienteController::class, 'muestraModal'])->name('muestraModal');

Route::resource('clientes', 'ClienteController');
Route::resource('gastos', 'GastoController');

//municipios

Route::get('municipios/creaMunicipio/{provincia}', [App\Http\Controllers\MunicipioController::class, 'creaMunicipio'])->name('creaMunicipio');
Route::get('municipios/muestraLocalidad/{provincia}', [App\Http\Controllers\MunicipioController::class, 'muestraLocalidad'])->name('muestraLocalidad');
Route::resource('municipios', 'MunicipioController');

//pagos
Route::get('pagos/muestraPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPago'])->name('muestraPago');
Route::get('pagos/createPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'createPago'])->name('createPago');

Route::delete('pagos/borraPago/{id}/{retorno}', [App\Http\Controllers\PagoController::class, 'borraPago'])->name('borraPago');

Route::get('pagos/editaPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'editaPago'])->name('editaPago');
Route::get('pagos/muestraPagoExtension/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPagoExtension'])->name('muestraPagoExtension');

Route::resource('pagos', 'PagoController');

//prestamos

Route::name('print')->get('/imprimir/{id}/{vehiculo_id}', 'GeneradorController@imprimir');

Route::get('prestamos/editaprestamo/{id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'editaprestamo'])->name('editaprestamo');
Route::get('prestamos/creaprestamo/{id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamo'])->name('creaprestamo');

Route::get('prestamos/listaprestamos/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamos'])->name('listaprestamos');
Route::get('prestamos/listaprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamoscliente'])->name('listaprestamoscliente');
Route::get('prestamos/ultimoprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'ultimoprestamoscliente'])->name('ultimoprestamoscliente');
//para mostrar las extensiones 02/10/2024

Route::get('prestamos/creaprestamoextension/{prestamo_id}/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamoextension'])->name('creaprestamoextension');
Route::get('prestamos/borraExtension/{prestamo_id}/{padre_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'borraExtension'])->name('borraExtension');

Route::resource('prestamos', 'PrestamoController');
Route::resource('provincias', 'ProvinciaController');

//vehiculos

Route::get('vehiculos/editavehiculo/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'editavehiculo'])->name('editavehiculo');
Route::get('vehiculos/createcliente/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'createcliente'])->name('createcliente');

Route::get('vehiculos/editavehiculo/{cliente}/modelosxmarcas2/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas2'])->name('modelosxmarcas2');

Route::get('vehiculos/createcliente/{cliente}/modelosxmarcas/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas'])->name('modelosxmarcas');

Route::get('vehiculos/listavehiculos/{idcliente}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'listavehiculos'])->name('listavehiculos');


//itv
Route::post('itv/muestraitv', [App\Http\Controllers\ItvController::class, 'muestraItv'])->name('muestraItv');
//Route::get('itv/elije', [App\Http\Controllers\ItvController::class, 'listaItv'])->name('listaItv');;
Route::resource('itv', 'ItvController');


//carnet de conducir
Route::post('carnet/muestraCarnet', [App\Http\Controllers\CarnetController::class, 'muestraCarnet'])->name('muestraCarnet');
Route::resource('carnet', 'CarnetController');

//polizas
Route::post('poliza/muestrapolizas', [App\Http\Controllers\PolizaController::class, 'muestraPolizas'])->name('muestraPolizas');
Route::resource('poliza', 'PolizaController');
//multas

Route::get('multa/createMultas/{id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'createMultas'])->name('createMultas');

Route::get('multa/muestraMultas/{id}/{motivo}/{vehiculo_id}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultas'])->name('muestraMultas');

Route::get('multa/general/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultasGeneral'])->name('muestraMultasGeneral');

Route::delete('multa/borraMulta/{id}/{cliente_id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'borraMulta'])->name('borraMulta');

Route::get('multa/editaMulta/{id}/{retorno}', [App\Http\Controllers\MultaController::class, 'editaMulta'])->name('editaMulta');

Route::resource('multas', 'MultaController');

Route::resource('vehiculos', 'VehiculoController');
Route::resource('users', 'UserController');

Route::get('muestraContratos/{cliente_id}/{prestamo_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\ContratoController::class, 'muestraContratos'])->name('muestraContratos');



//-----contratos ----
Route::get('contrato/index', [App\Http\Controllers\ContratoController::class, 'index'])->name('contratos');

    Route::name('CompraVenta')->get('/CompraVenta/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@CompraVenta');
    Route::name('DatosOperacion')->get('/DatosOperacion/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DatosOperacion');

    Route::name('DocumentoEntrega')->get('/DocumentoEntrega/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DocumentoEntrega');
    Route::name('EdicionCliente')->get('/EdicionCliente/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@EdicionCliente');
    Route::name('ContratoArrendamiento')->get('/ContratoArrendamiento/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@ContratoArrendamiento');
    Route::name('MandatoEspecifico')->get('/MandatoEspecifico/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@MandatoEspecifico');
    Route::name('ImpagoIndividual')->get('/ImpagoIndividual/{id}/{prestamo_id}', 'GeneradorController@ImpagoIndividual');

//mail

Route::get('mail/enviaMailPoliza', [App\Http\Controllers\MailController::class, 'enviaMailPoliza'])->name('enviaMailPoliza');

Route::get('mail/enviaMailitv', [App\Http\Controllers\MailController::class, 'enviaMailitv'])->name('enviaMailitv');
Route::get('mail/enviaMailCobranza', [App\Http\Controllers\MailController::class, 'enviaMailCobranza'])->name('enviaMailCobranza');

//reportes de rentabilidad

Route::get('rentabilidad/rentageneral/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\RentabilidadController::class, 'muestraRentabilidad'])->name('muestraRentabilidad');

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Cliente
 *
 * @property $id
 * @property $empresa_id
 * @property $nombre
 * @property $dni
 * @property $sexo
 * @property $provincia_id
 * @property $municipio_id
 * @property $direccion
 * @property $telefono
 * @property $email
 * @property $status
 * @property $nombre2
 * @property $dni2
 * @property $sexo2
 * @property $nombre_tutor
 * @property $tipo_tutor
 * @property $dni_tutor
 * @property $pespecial
 * @property $sexo_tutor
 * @property $dir_tutor
 * @property $pespecial
 * @property $propempresa
 * @property $dnicif
 * @property $codpostal
 * @property $fcarnet
 * @property $observacion
 * @property $created_at
 * @property $updated_at
 * @property $pnotarial
 * @property Empresa $empresa
 * @property Municipio $municipio
 * @property Prestamo[] $prestamos
 * @property Provincia $provincia
 * @property Vehiculo[] $vehiculos
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Cliente extends Model
{

    static $rules = [
        /*
		'empresa_id' => 'required',
		'nombre' => 'required',
		'dni' => 'required',
		'provincia_id' => 'required',
		'municipio_id' => 'required',
		'direccion' => 'required',
		'telefono' => 'required',
		'status' => 'required',
        */
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['empresa_id','nombre',
    'dni','sexo','provincia_id','municipio_id','direccion','telefono',
    'email','status','nombre2','dni2','sexo2','propempresa','dnicif','codpostal',
    'proempresa','observacion','fcarnet','nombre_tutor','tipo_tutor','dni_tutor','pespecial','sexo_tutor','pnotarial','dir_tutor','pespecial' ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function empresa()
    {
        //return $this->hasOne('App\Models\Empresa', 'id', 'empresa_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function municipio()
    {
        //return $this->hasOne('App\Models\Municipio', 'id', 'municipio_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function prestamos()
    {
        return $this->hasMany('App\Models\Prestamo', 'cliente_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function provincia()
    {
        //return $this->hasOne('App\Models\Provincia', 'id', 'provincia_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function vehiculos()
    {
        return $this->hasMany('App\Models\Vehiculo', 'cliente_id', 'id');
    }


}

resources/views/cliente/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Cliente
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Nuevo') }} Cliente</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('clientes.store') }}"  role="form" enctype="multipart/form-data" onkeydown="return event.key != 'Enter';">
                            @csrf
                            <?php
                                $nuevo=1;
                            ?>
                            <input type="hidden" name="nuevo" id="nuevo" value="<?php echo $nuevo; ?>">

                            @include('cliente.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cliente/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Cliente
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Editar') }} Cliente</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('clientes.update',$cliente) }}"  role="form" enctype="multipart/form-data" onkeydown="return event.key != 'Enter';">
                            
                            <?php
                                $nuevo=0;
                            ?>
                            <input type="hidden" name="nuevo" id="nuevo" value="<?php echo $nuevo; ?>">
                           

                            {{ method_field('PATCH') }}
                            @csrf
                            @include('cliente.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cliente/index.blade.php
@extends('layouts.app')

@section('template_title')
    Cliente
@endsection

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <span id="card_title">
                                {{ __('Clientes: '.$status) }}
                            </span>
                            <a href="{{route('home')}}"  ><div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a>
                             <div class="float-right">
                                @if($status=='')
                                <a href="{{ route('clientes.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                    {{ __('Nevo Cliente') }}
                                </a>
                                @endif
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                    @endif
                    <br>
                    <div class="card-body">
                        {!! $clientes->links() !!}
                        <div class="table-responsive">
                          <form action="{{route('clientes.index')}}">
                            <input type="text" name="texto" class="form-label" style="width:200px;">
                            <button type="submit" class="btn btn-primary">Buscar</button>
                          </form>

                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>Núm</th>
										<!--<th>Empresa</th>-->
										<th>Nombre</th>
										<th>DNI</th>
										<th>Vehículos</th>

                                        <th>Sit.<br>Carga</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $actual=0;
                                        $cadena=array();
                                        $cad=0;
                                    @endphp
                                    @foreach ($clientes as $cliente)
                                        <tr>
                                            <td>{{ ++$i }}</td>
											<td>
                                                @if($cliente->proempresa=='')
                                                    <a  href="{{ route('clientes.edit',$cliente->id) }}"> {{$cliente->nombres }}</a>
                                                @else
                                                <a  href="{{ route('clientes.edit',$cliente->id) }}"> {{$cliente->proempresa }}</a>
                                                @endif
                                            </td>
											<td>{{$cliente->dni }}</td>

                                            <td>
                                                @php
                                                $veh=array();
                                                $cont=count($vehiculosa);
                                                for ($p=0;$p<$cont;$p++){
                                                    if($cliente->id==$vehiculosa[$p]['id']){
                                                        $veh[]=array(
                                                            'idveh' => $vehiculosa[$p]['idveh'],
                                                            'matricula' => $vehiculosa[$p]['matricula']
                                                        );
                                                    }
                                                }

                                                $cont=count($veh);
                                                for($p=0;$p<$cont;$p++){
                                                    echo '<a  href="'.route('editavehiculo',[$veh[$p]['idveh'],7]) .'">'.$veh[$p]['matricula'].' </a>';
                                                    //echo '<a class="btn btn-sm empenos_btn btnn" href="{{route('listaprestamoscliente',[$cliente->id,1])}}"><i class="fa fa-fw fa-edit"></i> {{ __('Empeños') }}</a>';

                                                    if($cont>1)
                                                    echo '<br />';
                                                }
                                                @endphp
                                            </td>
                                            <td>
                                                @if(is_null($cliente->id))
                                                    <img src="{{ asset('images/rojo.jpg') }}" width="28" height="25">
                                                @else
                                                    <?php
                                                        $cad++;
                                                        $falta=cuenta_faltantes('clientes',$cliente->id,0,$cadena,$cad);
                                                    ?>
                                                    @if($falta==0)
                                                    <img src="{{ asset('images/verde.jpg') }}" width="28" height="25">
                                                    @else
                                                    <a href=""  data-toggle="modal" data-target="#myModal{{$cad}}">
                                                        <img src="{{ asset('images/rojo.jpg') }}" width="28" height="25">
                                                    </a>
                                                    @endif
                                                @endif
                                                <div class="modal " id="myModal{{$cad}}" role="dialog" >
                                                    <div class="modal-dialog">
                                                      <!-- Modal -->
                                                      <div class="modal-content" style="height:300px;width:300px;right: 350px;">
                                                        <div class="modal-header">
                                                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                          <h4 class="modal-title">Datos Faltantes</h4>
                                                        </div>
                                                        <div class="modal-body" >
                                                            <div>
                                                                @php
                                                                    echo $cadena[$cad];
                                                                @endphp
                                                              </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </td>

                                            <td>
                                            <form action="{{ route('clientes.destroy',$cliente->id) }}" method="POST" id="borrar">
                                                @csrf
                                                @method('DELETE')
                                                <input type="hidden" name="retorno" value="1">
                                <!--<a class="btn btn-sm btn-success btnn" href="{{ route('clientes.edit',$cliente->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Editar') }}</a>-->
                                <a class="btn btn-sm vehiculos_btn btnn" href="{{ route('listavehiculos',[$cliente->id,1]) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Vehículos') }}</a>
                                <a class="btn btn-sm empenos_btn btnn" href="{{route('listaprestamoscliente',[$cliente->id,0,1])}}"><i class="fa fa-fw fa-edit"></i> {{ __('Empeños') }}</a>
                                <a class="btn btn-sm documentos_btn btnn" href="{{route('muestraDocumentos',[$cliente->id,1,0])}}"><i class="fa fa-fw fa-edit"></i> {{ __('Documentos') }}</a>
                                <a  class="btn btn-danger btn-sm btnn" onclick="aviso({{$cliente->id}});"><i class="fa fa-fw fa-trash">{{ __('Borrar') }}</i></a>

                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $clientes->links() !!}
            </div>
        </div>
    </div>

@endsection
<script type="text/javascript">
    function aviso(id){
        var resp=confirm("¿Está seguro de eliminar este Cliente?");
        if(!resp){
            event.preventDefault();
            event.returnValue = '';
        }else{
            let url ="<?php echo env('APP_URL'); ?>";
            url=url +'/clientes/'+id;
            document.getElementById("borrar").action = url;

            document.getElementById("borrar").submit();
        }
    }
</script>


<script src="{{asset('modal/assets/jquery-1.12.4-jquery.min.js')}}"></script>
<script src="{{asset('modal/assets/jquery.validate.min.js')}}"></script>
<script src="{{asset('modal/dist/js/bootstrap.min.js')}}"></script>

resources/views/cliente/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $cliente->name ?? "{{ __('Show') Cliente" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Cliente</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('clientes.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Empresa Id:</strong>
                            {{ $cliente->empresa_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $cliente->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Dni:</strong>
                            {{ $cliente->dni }}
                        </div>
                        <div class="form-group">
                            <strong>Provincia Id:</strong>
                            {{ $cliente->provincia_id }}
                        </div>
                        <div class="form-group">
                            <strong>Municipio Id:</strong>
                            {{ $cliente->municipio_id }}
                        </div>
                        <div class="form-group">
                            <strong>Direccion:</strong>
                            {{ $cliente->direccion }}
                        </div>
                        <div class="form-group">
                            <strong>Telefono:</strong>
                            {{ $cliente->telefono }}
                        </div>
                        <div class="form-group">
                            <strong>Email:</strong>
                            {{ $cliente->email }}
                        </div>
                        <div class="form-group">
                            <strong>Status:</strong>
                            {{ $cliente->status }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection