routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('/home');
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/change-password', [App\Http\Controllers\HomeController::class, 'changePassword'])->name('change-password');

Route::post('/change-password', [App\Http\Controllers\HomeController::class, 'updatePassword'])->name('update-password');

Route::resource('bancos', 'BancoController');

Route::resource('clasificados', 'ClasificadoController');

//cobranzas
Route::get('cobranzas/muestraCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class, 'muestraCobranza'])->name('muestraCobranza');

Route::get('cobranzas/createCobranza/{id}/{motivo}', [App\Http\Controllers\CobranzaController::class,
'createCobranza'])->name('createCobranza');

Route::get('cobranzas/impagos/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\CobranzaController::class, 'impagos'])->name('impagos');

//Route::get('cobranzas/reporteImpagos/{cobranzas}', [App\Http\Controllers\CobranzaController::class, 'reporteImpagos'])->name('reporteImpagos');
Route::get('cobranzas/enviaMailCobranzaUno/{id}/{motivo}', [App\Http\Controllers\MailController::class, 'enviaMailCobranzaUno'])->name('enviaMailCobranzaUno');


Route::resource('cobranzas', 'CobranzaController');
Route::resource('empresas', 'EmpresaController');
Route::resource('empseguros', 'EmpseguroController');

Route::resource('marcas', 'MarcaController');
//modelos

Route::get('modelos/creaModelo/{marca}', [App\Http\Controllers\ModeloController::class, 'creaModelo'])->name('creaModelo');

Route::get('modelos/muestraModelos/{marca}', [App\Http\Controllers\ModeloController::class, 'muestraModelos'])->name('muestraModelos');
Route::get('modelos/borramodelos/{id}', [App\Http\Controllers\ModeloController::class, 'destroy'])->name('borramodelos');

Route::resource('modelos', 'ModeloController');



Route::get('clientes/municipiosbyprovincias/{id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias'])->name('municipiosbyprovincias');

Route::get('clientes/{cliente}/municipiosbyprovincias2/{provincia_id}', [App\Http\Controllers\ClienteController::class, 'municipiosbyprovincias2'])->name('municipiosbyprovincias2');

Route::get('clientes/clientesEspera', [App\Http\Controllers\ClienteController::class, 'clientesEspera'])->name('clientesEspera');
Route::get('clientes/muestraModal', [App\Http\Controllers\ClienteController::class, 'muestraModal'])->name('muestraModal');

Route::resource('clientes', 'ClienteController');
Route::resource('gastos', 'GastoController');

//municipios

Route::get('municipios/creaMunicipio/{provincia}', [App\Http\Controllers\MunicipioController::class, 'creaMunicipio'])->name('creaMunicipio');
Route::get('municipios/muestraLocalidad/{provincia}', [App\Http\Controllers\MunicipioController::class, 'muestraLocalidad'])->name('muestraLocalidad');
Route::resource('municipios', 'MunicipioController');

//pagos
Route::get('pagos/muestraPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPago'])->name('muestraPago');
Route::get('pagos/createPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'createPago'])->name('createPago');

Route::delete('pagos/borraPago/{id}/{retorno}', [App\Http\Controllers\PagoController::class, 'borraPago'])->name('borraPago');

Route::get('pagos/editaPago/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'editaPago'])->name('editaPago');
Route::get('pagos/muestraPagoExtension/{id}/{retorno}/{padre}', [App\Http\Controllers\PagoController::class, 'muestraPagoExtension'])->name('muestraPagoExtension');

Route::resource('pagos', 'PagoController');

//prestamos

Route::name('print')->get('/imprimir/{id}/{vehiculo_id}', 'GeneradorController@imprimir');

Route::get('prestamos/editaprestamo/{id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'editaprestamo'])->name('editaprestamo');
Route::get('prestamos/creaprestamo/{id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamo'])->name('creaprestamo');

Route::get('prestamos/listaprestamos/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamos'])->name('listaprestamos');
Route::get('prestamos/listaprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'listaprestamoscliente'])->name('listaprestamoscliente');
Route::get('prestamos/ultimoprestamoscliente/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'ultimoprestamoscliente'])->name('ultimoprestamoscliente');
//para mostrar las extensiones 02/10/2024

Route::get('prestamos/creaprestamoextension/{prestamo_id}/{cliente_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'creaprestamoextension'])->name('creaprestamoextension');
Route::get('prestamos/borraExtension/{prestamo_id}/{padre_id}/{retorno}', [App\Http\Controllers\PrestamoController::class, 'borraExtension'])->name('borraExtension');

Route::resource('prestamos', 'PrestamoController');
Route::resource('provincias', 'ProvinciaController');

//vehiculos

Route::get('vehiculos/editavehiculo/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'editavehiculo'])->name('editavehiculo');
Route::get('vehiculos/createcliente/{id}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'createcliente'])->name('createcliente');

Route::get('vehiculos/editavehiculo/{cliente}/modelosxmarcas2/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas2'])->name('modelosxmarcas2');

Route::get('vehiculos/createcliente/{cliente}/modelosxmarcas/{marca_id}', [App\Http\Controllers\VehiculoController::class, 'modelosxmarcas'])->name('modelosxmarcas');

Route::get('vehiculos/listavehiculos/{idcliente}/{retorno}', [App\Http\Controllers\VehiculoController::class, 'listavehiculos'])->name('listavehiculos');


//itv
Route::post('itv/muestraitv', [App\Http\Controllers\ItvController::class, 'muestraItv'])->name('muestraItv');
//Route::get('itv/elije', [App\Http\Controllers\ItvController::class, 'listaItv'])->name('listaItv');;
Route::resource('itv', 'ItvController');


//carnet de conducir
Route::post('carnet/muestraCarnet', [App\Http\Controllers\CarnetController::class, 'muestraCarnet'])->name('muestraCarnet');
Route::resource('carnet', 'CarnetController');

//polizas
Route::post('poliza/muestrapolizas', [App\Http\Controllers\PolizaController::class, 'muestraPolizas'])->name('muestraPolizas');
Route::resource('poliza', 'PolizaController');
//multas

Route::get('multa/createMultas/{id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'createMultas'])->name('createMultas');

Route::get('multa/muestraMultas/{id}/{motivo}/{vehiculo_id}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultas'])->name('muestraMultas');

Route::get('multa/general/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'muestraMultasGeneral'])->name('muestraMultasGeneral');

Route::delete('multa/borraMulta/{id}/{cliente_id}/{vehiculo_id}/{motivo}/{retorno}', [App\Http\Controllers\MultaController::class, 'borraMulta'])->name('borraMulta');

Route::get('multa/editaMulta/{id}/{retorno}', [App\Http\Controllers\MultaController::class, 'editaMulta'])->name('editaMulta');

Route::resource('multas', 'MultaController');

Route::resource('vehiculos', 'VehiculoController');
Route::resource('users', 'UserController');

Route::get('muestraContratos/{cliente_id}/{prestamo_id}/{vehiculo_id}/{retorno}', [App\Http\Controllers\ContratoController::class, 'muestraContratos'])->name('muestraContratos');



//-----contratos ----
Route::get('contrato/index', [App\Http\Controllers\ContratoController::class, 'index'])->name('contratos');

    Route::name('CompraVenta')->get('/CompraVenta/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@CompraVenta');
    Route::name('DatosOperacion')->get('/DatosOperacion/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DatosOperacion');

    Route::name('DocumentoEntrega')->get('/DocumentoEntrega/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@DocumentoEntrega');
    Route::name('EdicionCliente')->get('/EdicionCliente/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@EdicionCliente');
    Route::name('ContratoArrendamiento')->get('/ContratoArrendamiento/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@ContratoArrendamiento');
    Route::name('MandatoEspecifico')->get('/MandatoEspecifico/{id}/{vehiculo_id}/{prestamo_id}', 'GeneradorController@MandatoEspecifico');
    Route::name('ImpagoIndividual')->get('/ImpagoIndividual/{id}/{prestamo_id}', 'GeneradorController@ImpagoIndividual');

//mail

Route::get('mail/enviaMailPoliza', [App\Http\Controllers\MailController::class, 'enviaMailPoliza'])->name('enviaMailPoliza');

Route::get('mail/enviaMailitv', [App\Http\Controllers\MailController::class, 'enviaMailitv'])->name('enviaMailitv');
Route::get('mail/enviaMailCobranza', [App\Http\Controllers\MailController::class, 'enviaMailCobranza'])->name('enviaMailCobranza');

//reportes de rentabilidad

Route::get('rentabilidad/rentageneral/{imprimir}/{mesesimpago2}/{texto2}', [App\Http\Controllers\RentabilidadController::class, 'muestraRentabilidad'])->name('muestraRentabilidad');

app/Models/Modelo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Modelo
 *
 * @property $id
 * @property $marca_id
 * @property $nombre
 * @property $created_at
 * @property $updated_at
 *
 * @property Marca $marca
 * @property Vehiculo[] $vehiculos
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Modelo extends Model
{
    
    static $rules = [
		'marca_id' => 'required',
		'nombre' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['marca_id','nombre'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function marca()
    {
        return $this->hasOne('App\Models\Marca', 'id', 'marca_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function vehiculos()
    {
        return $this->hasMany('App\Models\Vehiculo', 'modelo_id', 'id');
    }
    

}

app/Http/Controllers/ModeloController.php
<?php

namespace App\Http\Controllers;

use App\Models\Modelo;
use App\Models\Marca;
use App\Models\Vehiculo;
use Illuminate\Http\Request;

/**
 * Class ModeloController
 * @package App\Http\Controllers
 */
class ModeloController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $modelos = Modelo::paginate();

        return view('modelo.index', compact('modelos'))
            ->with('i', (request()->input('page', 1) - 1) * $modelos->perPage());
    }
    public function muestraModelos(Request $request,$id)
    {

        $modelo=$request->modelo;
        //$modelos = Modelo::paginate();
        $modelos = Marca::where('marcas.id','=',$id)
        ->where('modelos.nombre','like','%'.$modelo.'%')
        ->leftjoin('modelos','modelos.marca_id','=','marcas.id')
        ->select('modelos.*','marcas.id as mar','marcas.nombre as nmar','modelos.nombre as nmod')
        ->orderby('modelos.nombre','asc')
        ->paginate();
        $i=0;

        return view('modelo.index', compact('modelos','id'))
            ->with('i', (request()->input('page', 1) - 1) * $modelos->perPage());
    }
    public function creaModelo($marca)
    {
        $modelo = new Modelo();
        $modelo->marca_id=$marca;
        return view('modelo.create', compact('modelo','marca'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $modelo = new Modelo();
        return view('modelo.create', compact('modelo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Modelo::$rules);

        $modelo = Modelo::create($request->all());
        $id=$request->marca_id;
            /* return redirect()
    ->action('ModeloController@muestraModelos', $id)
    ->with('success', 'Modelo creado con Exito.'); */
    return redirect()
    ->action('MarcaController@edit', $id)
    ->with('success', 'Modelo creado con Exito.');

        //return redirect()->route('modelos.index')
          //  ->with('i','success', 'Modelo creado con Exito.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $modelo = Modelo::find($id);

        return view('modelo.show', compact('modelo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $modelo = Modelo::find($id);
        $marca=$modelo->marca_id;
        return view('modelo.edit', compact('modelo','marca'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Modelo $modelo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Modelo $modelo)
    {
        request()->validate(Modelo::$rules);
        $modelo->update($request->all());
        $id=$request->marca_id;
        return redirect()
        ->action('MarcaController@edit', $id)
        ->with('success', 'Modelo modificado con Exito.');

    /* return redirect()
    ->action('ModeloController@muestraModelos', $id)
    ->with('success', 'Modelo modificado con Exito.'); */
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $modelo=Modelo::find($id);
        $marca_id=$modelo->marca_id;
        $vehiculos=Vehiculo::where('vehiculos.modelo_id','=',$id)->selectRaw('count(*) as tveh')->get();
        $tvehiculos=0;

        foreach($vehiculos as $tveh){
            $tvehiculos=$tveh->tveh;
        }
        if($tvehiculos==0){
            $modelo = Modelo::find($id)->delete();
            $smj='Modelo eliminado con Exito.';
        }else{
            $smj='No se puede eliminar porque tiene Vehiculos relacionados.';
        }
        return redirect()
        ->action('MarcaController@edit', $marca_id)
        ->with('success', $smj);
        /* return redirect()
        ->action('ModeloController@muestraModelos', $marca_id)
        ->with('success', $smj); */

        //return redirect()->route('modelos.index')
          //  ->with('success', 'Modelo eliminado con Exito');
    }
}

resources/views/modelo/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Modelo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Nuevo') }} Modelo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('modelos.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('modelo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/modelo/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Modelo
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Modificar') }} Modelo</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('modelos.update', $modelo->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('modelo.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/modelo/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            <!--{{ Form::label('marca_id') }}-->
            {{ Form::hidden('marca_id', $modelo->marca_id, ['class' => 'form-control' . ($errors->has('marca_id') ? ' is-invalid' : ''), 'placeholder' => 'Marca Id']) }}
            {!! $errors->first('marca_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $modelo->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('Guardar') }}</button>
        <a href="{{route('marcas.edit',$marca)}}"  ><div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a>
    </div>
</div>

resources/views/modelo/index.blade.php
{{-- @extends('layouts.app')

@section('template_title')
    Modelo
@endsection
 --}}
{{-- @section('content') --}}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <span id="card_title">
                                {{ __('Modelos') }}
                            </span>
                            {{-- <a href="{{route('marcas.index')}}"  ><div class="grid-item5 btn btn-primary" style="background-color: yellow;color:black;">Volver</div></a> --}}

                             {{-- <div class="float-right">
                                <a href="{{ route('creaModelo',$id) }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Nuevo Modelo') }}
                                </a>
                              </div> --}}
                              <div class="float-right">
                                <a href="{{ route('creaModelo',$marca->id) }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Nuevo Modelo') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        {!! $modelos->links() !!}
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>Núm</th>
										{{-- <th>Marca</th> --}}
										<th>Modelo</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <form action="{{url('modelos.destroy',0)}}" method="POST" id ="borrarmodelo">
                                    </form>
                                    @foreach ($modelos as $modelo)
                                        <tr>
                                            <td>{{ ++$i }}</td>
											{{-- <td>{{ $modelo->nmar }}</td> --}}
											<td>{{ $modelo->nombre }}</td>
                                            <td>
                                                <form action="{{url('modelos.destroy',$modelo->id)}}" method="POST" id ="borrarmodelo">
                                                    <a class="btn btn-sm btn-success" href="{{ route('modelos.edit',$modelo->id) }}">
                                                        <i class="fa fa-fw fa-edit"></i> {{ __('Editar') }}
                                                    </a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <a onclick="avisomodelo({{$modelo->id}});" class="btn btn-danger btn-sm btnn"><i class="fa fa-fw fa-trash">{{ __('Borrar') }}</i> </a>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $modelos->links() !!}
            </div>
        </div>
    </div>
{{-- @endsection --}}
<script type="text/javascript">
    function avisomodelo(id){
        var resp=confirm("¿Está seguro de eliminar este Modelo?");
        if(!resp){
            event.preventDefault();
            event.returnValue = '';
        }else{
            let url ="<?php echo env('APP_URL'); ?>";
            url1=url+'/modelos/'+id;
            //alert(url);
            document.getElementById("borrarmodelo").action=url1;
            document.getElementById("borrarmodelo").submit();
        }
    }
</script>

resources/views/modelo/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $modelo->name ?? "{{ __('Show') Modelo" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Modelo</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('modelos.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Marca Id:</strong>
                            {{ $modelo->marca_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $modelo->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection